server:
  port: 8081
spring:
  application:
    name: MailService
  mail:
    host: smtp.ethereal.email
    port: 587
    username : lonzo.oreilly22@ethereal.email
    password : vttdekdffJ233MVjnd
    properties:
     mail:
      smtp:
       auth: true
       starttls:
        enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbit:
  queue:
    email: email.direct
mail:
  from:
    address: noreply@monitor.com
  subject: Notification from Monitor system